### ISSUE TITLE
Containerized Alpine support

### ISSUE THREAD

**Issue by mvorisek** [hendrikmuhs/ccache-action#131]
Please add support for Alpine, currently, `apt` is tried to be used to install `ccache` but Alpine needs `ccache`.

CI repro: https://github.com/php/php-src/actions/runs/4083551771/jobs/7039218638#step:6:18

Example GH workflow:
```
    runs-on: ubuntu-20.04
    container:
      image: alpine:3.15
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
```
