### ISSUE TITLE
`Post Setup ccache` not displaying correctly when using bash on Windows

### ISSUE THREAD

**Issue by juan-lunarg** [hendrikmuhs/ccache-action#148]
The `Post Setup ccache` doesn't work correctly on our MinGW workflow. Led to minor confusion.
```
Post job cleanup.
ccache stats
  C:\ProgramData\Chocolatey\bin\ccache.exe -s
  cache directory                     C:\Users\runneradmin\AppData\Roaming/ccache
  primary config                      C:\Users\runneradmin\AppData\Roaming/ccache/ccache.conf
  secondary config (readonly)         R:/winlibs64_stage/inst_ccache-4.3/etc/ccache.conf
  cache hit (direct)                     0
  cache hit (preprocessed)               0
  cache miss                             0
  cache hit rate                      0.00 %
  cleanups performed                     0
  files in cache                         0
  cache size                           0.0 kB
  max cache size                       5.0 GB
Save cache using key "ccache-mingw-ccache-2023-05-24T20:10:55.447Z".
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/Vulkan-ValidationLayers/Vulkan-ValidationLayers --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
Cache Size: ~27 MB (27829669 B)
Cache saved successfully
```

However when I run `ccache --show-stats` directly after the build it shows the hits properly

Here is a github action that should show the behavior.

```yml
  mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: mingw-ccache
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: lukka/get-cmake@latest
      - name: GCC Version
        run: gcc --version # If this fails MINGW is not setup correctly
      - name: Configure
        run: cmake -S. -B build-D CMAKE_BUILD_TYPE=Release
        env:
          LDFLAGS: -fuse-ld=lld # MINGW linking is very slow. Use llvm linker instead.
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          CMAKE_GENERATOR: Ninja
      - name: Build
        run: cmake --build build -- --quiet
      - name: Install
        run: cmake --install build --prefix build/install
      - name: MinGW ccache stats
        run: ccache --show-stats  # <----------------- The Post Setup ccache doesn't work right on MinGW
```

Link to PR where I discovered this:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5904
