### ISSUE TITLE
Not using latest cache key?

### ISSUE THREAD

**Issue by Alexander-Wilms** [hendrikmuhs/ccache-action#164]
Using your action like this

```
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          key: ${{ matrix.preset }}
[...]
    - name: CMake Preset
      run: |
        cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache --preset ${{ matrix.preset }}
```

I saw the following:

![image](https://github.com/hendrikmuhs/ccache-action/assets/3226457/a66050cd-d859-45c5-bd96-f67a573774bf)

![image](https://github.com/hendrikmuhs/ccache-action/assets/3226457/7f510bd4-97b5-42c2-a285-4a31a1910569)

Note the timeline:

CI run 1 succeeded 42 min ago and saved the cache using the key `ccache-linux-gcc-test-2023-09-28T17:29:31.499Z`
CI run 2 started 14 min ago and restored the cache using the key `ccache-linux-gcc-test-2023-09-28T16:08:40.914Z`

Is this due to Github not guaranteeing to use the latest cache, perhaps because it takes some time to copy the data to the runners?

I think it's not that important, since usually commits only touch a few files, but it was still unexpected.
