### ISSUE TITLE
Better caching for pull requests

### ISSUE THREAD

**Issue by Alexander-Wilms** [hendrikmuhs/ccache-action#168]
Since pull requests touch a lot of different files, ccache reports a lot of cache misses if they all use the same key (with the timestamp postfix).

It would be nice if the first CI of a PR run would read the cache written by the latest CI run of the repo's master branch and then write and read the cache using a key that has the PR ID appended to it.

This way, the PRs wouldn't interfere with each other and the first CI run would still be quite fast.

In order to realize this, additional keys would need to be added.

Perhaps something like this:

```
- uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

- name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          if: github.event_name == 'pull_request'
                  key-read: ${{ matrix.preset }}-${{ steps.PR.outputs.number }}
                  key-read-fallback: ${{ matrix.preset }}
                  key-write: ${{ matrix.preset }}-${{ steps.PR.outputs.number }}
          else:
                  key: ${{ matrix.preset }}
```

**Comment by Alexander-Wilms** [comment]
Just discovered that this is already possible: https://github.com/hendrikmuhs/ccache-action/blob/main/action.yml#L8C3-L8C16


```yaml
- uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

- name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          if: github.event_name == 'pull_request'
                  key: ${{ matrix.preset }}-${{ steps.PR.outputs.number }}
          else:
                  key: ${{ matrix.preset }}
          restore-keys: |
            ${{ matrix.preset }}-${{ steps.PR.outputs.number }}
            ${{ matrix.preset }}
```
