### ISSUE TITLE
Setting append-timestamp to false appended trailing `-`

### ISSUE THREAD

**Issue by Naros** [hendrikmuhs/ccache-action#302]
Given the following step definition:
```
    - name: Restore cache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.cache-name }}|${{ github.ref_name }}|${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-name }}|${{ github.ref_name }}
          ${{ inputs.cache-name }}|${{ github.event.repository.default_branch }}
        append-timestamp: false
```
I expect the cache action to find `<name>|<ref-name>|<sha>` and fall back to one of the others if it isn't found. This will be pretty common if you append a new commit to a PR and the `github.sha` changes; however, because the action appends a trailing `-` to the cache name, none of the restore keys effectively match it, seen here:
```
Warning: Cache not found for keys: ccache-android-template-arm32|931/merge|b2ac108f207a41ffa6a0a016ec3934babb5ded51-, ccache-android-template-arm32|931/merge-, ccache-android-template-arm32|main-
```
This effectively makes setting `append-timestamp: false` useless because it won't ever use the restore-keys.
